#!/bin/bash

echo "Please enter a new hostname (or press Enter to skip):"
read -r NEW_HOSTNAME
if [ -n $NEW_HOSTNAME ]; then
  sudo sh -c "echo $NEW_HOSTNAME > /etc/hostname" &&
  sudo hostname "$new_hostname"
else
  echo "Hostname skipped"
fi

echo "--------------Installing Ubuntu packages...----------------------"
sudo apt-get update
echo "----updating nodejs repo source------"
curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
echo ""
sudo apt-get install -y openssl language-pack-zh-hans git-core wget vim zsh
echo "---------------------------------------------------------------------------"
echo "--------------Installed Ubuntu packages------------------------"
echo ""
echo "--------------Installing zh_CN locale------------------------"
sudo sh -c "echo 'Asia/Beijing' > /etc/timezone"
dpkg-reconfigure -f noninteractive tzdata

echo 'export LANG="zh_CN.UTF-8"' >> ~/.profile
echo 'export LC_ALL="zh_CN.UTF-8"' >> ~/.profile
sudo locale-gen zh_CN.UTF-8
locale
echo "--------------Installed zh_CN locale------------------------"
echo ""
echo ""
echo "--------------Adding 1G Swap Memory------------------------"
sudo fallocate -l 1G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
sudo sh -c "echo '/swapfile swap swap defaults 0 0' >> /etc/fstab"
sudo free -h
echo "--------------Added Swap Memory------------------------"
echo ""
