#!/bin/bash
 
echo "Enter environments for traefik and portainer"
read -p "EMAIL: " email
read -p "WILD_DOMAIN: " wild_domain
read -p "USERNAME: " username
read -p "PASSWORD: " password

export EMAIL=$email
export WILD_DOMAIN=$wild_domain
export USERNAME=$username
export PASSWORD=$password
export HASHED_PASSWORD=$(openssl passwd -apr1 $PASSWORD)
export TRAEFIK_REPLICAS=1

echo "Environments successfully set!"

echo "Downloading docker-compose files..."

curl https://git.yingxuan.io/yx/init-d/-/raw/master/docker-swarm/traefik.yml > traefik.yml
curl https://git.yingxuan.io/yx/init-d/-/raw/master/docker-swarm/portainer-agent-stack.yml > portainer-agent-stack.yml

echo "Deploying traefik..."
docker stack deploy -c traefik.yml traefik

echo "Deploying portainer..."
docker stack deploy -c portainer-agent-stack.yml portainer

docker ps

echo "If you could see docker containers running now, they were successfully deployed!"
