version: '3.4'

services:
  traefik:
    image: traefik:v2.2
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    deploy:
      replicas: ${TRAEFIK_REPLICAS:-3}
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.http.routers.api.rule=Host(`traefik.${DOMAIN?Variable DOMAIN not set}`)
        - traefik.http.routers.api.service=api@internal
        - traefik.http.routers.api.tls
        - traefik.http.routers.api.tls.certresolver=myresolver
        - traefik.http.services.traefik.loadbalancer.server.port=8080
        # Traefik service that listens to HTTP，添加 basic auth 验证
        - traefik.http.routers.api.middlewares=https_redirect,auth
        - traefik.http.middlewares.https_redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https_redirect.redirectscheme.permanent=true
        - traefik.http.middlewares.auth.basicauth.users=${USERNAME?Variable USERNAME not set}:${HASHED_PASSWORD?Variable HASHED_PASSWORD not set}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
    command: >
      --providers.docker=true
      --providers.docker.endpoint=unix:///var/run/docker.sock
      --providers.docker.swarmMode=true
      --providers.docker.watch=true
      --providers.docker.exposedByDefault=false
      --entrypoints.web.address=:80
      --entrypoints.websecure.address=:443
      --entrypoints.web.http.redirections.entrypoint.to=websecure
      --entrypoints.web.http.redirections.entrypoint.scheme=https
      --certificatesresolvers.myresolver.acme.email=${EMAIL?Variable EMAIL not set}
      --certificatesresolvers.myresolver.acme.storage=acme.json
      --certificatesResolvers.myresolver.acme.httpChallenge.entryPoint=web
      --certificatesResolvers.myresolver.acme.tlsChallenge=true
      --log.Level=INFO
      --metrics.prometheus=true
      --metrics.prometheus.entryPoint=web
      --accessLog
      --api
    networks:
      - traefik

networks:
  traefik:
    external: true
